// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxvaltsfaeadovwzgapy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dmFsdHNmYWVhZG92d3pnYXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNDE1MTIsImV4cCI6MjA3NzgxNzUxMn0.akzEopgYolGYFRhdQtzA-QRa7G4-6mLPSYeHI4TyCSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});